In [1]:
# 라이브러리 불러오기
import numpy as np

In [4]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
     - 기본값(axis = -1) : 현재 배열의 마지막 axis
     - axis = 0 : 열 단위 정렬
     - axis = 1 : 행 단위 정렬
     - 정렬된 새로운 배열을 반환함
     
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 ㅈ어렬

In [5]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    dimension : 1
    dtype : int32
    data : 
 [0 1 2 3 4]


In [8]:
# 기존 파이썬 문법으로 순번 뒤집기
x[::-1]

array([4, 3, 2, 1, 0])

In [13]:
# 난수 고정값는 1515
np.random.seed(1515)

In [ ]:
# 오름차순 정렬 테스트용 난수배열 만들기
# 0이상 9이하 숫자 5개를 난수생서으로 만들어서 찍어주세요

In [14]:
a = np.random.randint(0, 9, size=5)
a

array([7, 8, 6, 7, 3])

In [15]:
# np.sort(자료) -> 원본 자료에 반영되진 않음
np.sort(a)

array([3, 6, 7, 7, 8])

In [17]:
# 자료.sort() -> 원본자료 변경
a.sort()
a

array([3, 6, 7, 7, 8])

In [18]:
b = np.random.randint(0, 10, 5)
b

array([2, 4, 9, 1, 7])

In [19]:
# np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해서는
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌  
# !!!!!!!인덱스번호임!!!!!!!!!!
np.argsort(b)

array([3, 0, 1, 4, 2], dtype=int64)

In [20]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
# np.random.random 을 이용하세요
a = np.random.random((3, 3))
b = np.random.random(9).reshape(3, 3)

In [21]:
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.49951145 0.47107893 0.72328324]
 [0.10641408 0.0314212  0.47031197]
 [0.50199779 0.23841375 0.56067134]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.31397076 0.58970362 0.47431556]
 [0.04606234 0.23922061 0.81511325]
 [0.92654299 0.16002479 0.28410932]]


#### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1<br>
마지막 axis = 1 (열별 정렬)
<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [24]:
# 기본방향 (axis=-1) => 열별 정렬
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.49951145 0.47107893 0.72328324]
 [0.10641408 0.0314212  0.47031197]
 [0.50199779 0.23841375 0.56067134]]


array([[0.47107893, 0.49951145, 0.72328324],
       [0.0314212 , 0.10641408, 0.47031197],
       [0.23841375, 0.50199779, 0.56067134]])

##### axis = 0 (열병정렬)

<img src='img/sortaxis0.jpg' widt='200' height='200' align='left'>

In [26]:
# 열별 정렬을 시켜보세요
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.49951145 0.47107893 0.72328324]
 [0.10641408 0.0314212  0.47031197]
 [0.50199779 0.23841375 0.56067134]]


array([[0.10641408, 0.0314212 , 0.47031197],
       [0.49951145, 0.23841375, 0.56067134],
       [0.50199779, 0.47107893, 0.72328324]])

### 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱: 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개
    
- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [28]:
# 0 ~ 23 구간으로 1씩 증가하는 값을 아이템으로 가지는 1차원 배열을 생성해주세요
arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int32
    data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [30]:
# 1차원 배열 인덱싱 : 1차원 인덱스 요소 접근
arr1[1]

1

In [31]:
# 1차원 배열 인덱싱 : 마지막 요소 접근
arr1[-1]

23

In [33]:
# arr1의 마지막 값을 100으로 고쳐주세요
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [34]:
# 배열 arr1을 이용해서 4 * 6 형태의 2차원 배열 arr2 만들기
arr2 = arr1.reshape(4, 6)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (4, 6)
    dimension : 2
    dtype : int32
    data : 
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]


In [35]:
# 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]
# 하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [56]:
# 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접근
# 반환값 : 1d array
arr2[:,0]

array([ 0,  6, 12, 18])

In [57]:
# 하나의 값에 접근
# 3행 3열(0번째부터 세서 3행)
arr2[3,3]

21

In [63]:
# 여러개의 행 조회(2차원배열로 조회)
# 0번, 3번 행 만 조회
arr2[[0,3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [66]:
# 여러개의 열 조회(0번째, 2번째 열만 선택해서 조회)
arr2[:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [67]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하려는 값을 스칼라값으로 전달
# 서로 다른 값으로 수정 : 배열 요소 개수에 맞춰서 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [68]:
# 단일 값이 아닌 여러 값을 대입하고 싶으면 모양에 맞게 배열을 대입합니다
arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [75]:
# 3차원 배열 생성
# 구조 : 2개의 층(면), 4행 3열
# np.arange() => 0 ~ 23까지 24개를 집어넣고 3차원으로 재조정해보세요
arr3 = np.arange(0, 24).reshape(2, 4, 3)
np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (2, 4, 3)
    dimension : 3
    dtype : int32
    data : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [76]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
# 0번째 면, 첫번째 행에 접근시켜주세요
arr3[0,1]

array([3, 4, 5])

In [81]:
# 1번째 면, 2번 행, 2번 열에 접근
arr3[1, 2, 2]

20

In [82]:
# 한 면을 통째로 바꾸고 싶다면 같은 크기의 2차원 배열을 대입해줍니다
arr3[0] = [[10, 20, 30],
[40, 50, 60],
[0, 0, 0],
[0, 0, 0]]

In [83]:
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [84]:
# 여러개의 인덱싱을 배열로 전달
# (행0, 열0), (행1, 열1), (행2, 열2)
# 3차원 배열일 경우에 : [페이지, [[0, 1, 2], [0, 1, 2]]]
# arr3[면, 행, 열] -> 만약 여러 단위를 조회할 대는 이중리스트로 입력
# 삼중리스트 입력시 이중리스트 요소를 반복
print(arr3[0])
print("----------------------")
print(arr3[0, [[0, 1, 2],[0, 2, 3]]])

[[10 20 30]
 [40 50 60]
 [ 0  0  0]
 [ 0  0  0]]
----------------------
[[[10 20 30]
  [40 50 60]
  [ 0  0  0]]

 [[10 20 30]
  [ 0  0  0]
  [ 0  0  0]]]


In [85]:
# 내부 요소 인덱싱시 일반 리스트를 사용하는 경우
# 줄 단위로 가져오는게 아니라 내부 요소 하나하나를 단위로 가져옴
arr3[0, [0, 1, 2], [0, 1, 2]]

array([10, 50,  0])