In [3]:
# 라이브러리 불러오기
import numpy as np

In [4]:
# Numpy 객체 정보를 확인하기 위한 사용자 함수 정의 : 객체타입, 구조, 차원, 데이터타입
def np_print(arr):
    text="""
    type : {}
    shape : {}
    dimension : {}
    dtype : {}
    data : \n {}""".format(type(arr), arr.shape, arr.ndim, arr.dtype, arr)
    print(text)

### 배열 정렬

- sort(axis = -1) 메서드 : axis를 기준으로 요소를 오름차순 정렬
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 정렬
    - 원본 객체에 정렬 결과가 반영됨
    
- np.sort(axis = -1) : axis를 기준으로 요소를 오름차순 정렬
     - 기본값(axis = -1) : 현재 배열의 마지막 axis
     - axis = 0 : 열 단위 정렬
     - axis = 1 : 행 단위 정렬
     - 정렬된 새로운 배열을 반환함
     
- np.argsort(arr) : 정렬 순서를 반환
    - 기본값(axis = -1) : 현재 배열의 마지막 axis
    - axis = 0 : 열 단위 정렬
    - axis = 1 : 행 단위 ㅈ어렬

In [5]:
# 1차원 배열 생성
x = np.arange(0, 5)
np_print(x)


    type : <class 'numpy.ndarray'>
    shape : (5,)
    dimension : 1
    dtype : int32
    data : 
 [0 1 2 3 4]


In [6]:
# 기존 파이썬 문법으로 순번 뒤집기
x[::-1]

array([4, 3, 2, 1, 0])

In [7]:
# 난수 고정값는 1515
np.random.seed(1515)

In [8]:
# 오름차순 정렬 테스트용 난수배열 만들기
# 0이상 9이하 숫자 5개를 난수생서으로 만들어서 찍어주세요

In [9]:
a = np.random.randint(0, 9, size=5)
a

array([7, 8, 6, 7, 3])

In [10]:
# np.sort(자료) -> 원본 자료에 반영되진 않음
np.sort(a)

array([3, 6, 7, 7, 8])

In [11]:
# 자료.sort() -> 원본자료 변경
a.sort()
a

array([3, 6, 7, 7, 8])

In [12]:
b = np.random.randint(0, 10, 5)
b

array([2, 4, 9, 1, 7])

In [13]:
# np.argsort(자료)는 내부의 아이템들을 오름차순 정렬하기 위해서는
# 현재 몇 번 인덱스에 있는 자료를 어디에 배치해야 하는지 보여줌  
# !!!!!!!인덱스번호임!!!!!!!!!!
np.argsort(b)

array([3, 0, 1, 4, 2], dtype=int64)

In [14]:
# 0이상 1미만의 범위에서 무작위로 실수값을 가지는 3행 3열의 배열 2개 생성
# np.random.random 을 이용하세요
a = np.random.random((3, 3))
b = np.random.random(9).reshape(3, 3)

In [15]:
np_print(a)
np_print(b)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.49951145 0.47107893 0.72328324]
 [0.10641408 0.0314212  0.47031197]
 [0.50199779 0.23841375 0.56067134]]

    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.31397076 0.58970362 0.47431556]
 [0.04606234 0.23922061 0.81511325]
 [0.92654299 0.16002479 0.28410932]]


#### 예) 2차원 배열의 경우

기본값 axis = -1 <br>
현재 배열의 axis = 0, 1<br>
마지막 axis = 1 (열별 정렬)
<img src='img/sortaxis1.jpg' width='200' height='200' align='left'>

In [16]:
# 기본방향 (axis=-1) => 열별 정렬
np_print(a)
np.sort(a)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.49951145 0.47107893 0.72328324]
 [0.10641408 0.0314212  0.47031197]
 [0.50199779 0.23841375 0.56067134]]


array([[0.47107893, 0.49951145, 0.72328324],
       [0.0314212 , 0.10641408, 0.47031197],
       [0.23841375, 0.50199779, 0.56067134]])

##### axis = 0 (열병정렬)

<img src='img/sortaxis0.jpg' widt='200' height='200' align='left'>

In [17]:
# 열별 정렬을 시켜보세요
np_print(a)
np.sort(a, axis=0)


    type : <class 'numpy.ndarray'>
    shape : (3, 3)
    dimension : 2
    dtype : float64
    data : 
 [[0.49951145 0.47107893 0.72328324]
 [0.10641408 0.0314212  0.47031197]
 [0.50199779 0.23841375 0.56067134]]


array([[0.10641408, 0.0314212 , 0.47031197],
       [0.49951145, 0.23841375, 0.56067134],
       [0.50199779, 0.47107893, 0.72328324]])

### 인덱싱(Indexing), 슬라이싱(Slicing)

### 1. 인덱싱: 하나의 요소에 대해 참조
- 각 차원에 따라 배열이 참조하는 인덱스의 개수가다름
    - 1차원 배열 : 인덱스 1개
    - 2차원 배열 : 인덱스 2개
    - 3차원 배열 : 인덱스 3개
    
- 인덱싱으로 참조한 요소에 대해 수정 가능

- 인덱스 배열을 전달하여 여러 개의 요소 참조

In [18]:
# 0 ~ 23 구간으로 1씩 증가하는 값을 아이템으로 가지는 1차원 배열을 생성해주세요
arr1 = np.arange(0, 24)
np_print(arr1)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int32
    data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [19]:
# 1차원 배열 인덱싱 : 1차원 인덱스 요소 접근
arr1[1]

1

In [20]:
# 1차원 배열 인덱싱 : 마지막 요소 접근
arr1[-1]

23

In [21]:
# arr1의 마지막 값을 100으로 고쳐주세요
arr1[-1] = 100
arr1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22, 100])

In [22]:
# 배열 arr1을 이용해서 4 * 6 형태의 2차원 배열 arr2 만들기
arr2 = arr1.reshape(4, 6)
np_print(arr2)


    type : <class 'numpy.ndarray'>
    shape : (4, 6)
    dimension : 2
    dtype : int32
    data : 
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22 100]]


In [23]:
# 2차원 배열 인덱싱 : 2차원배열[행인덱스, (열인덱스)]
# 하나의 행에 접근 : 1행
arr2[0]

array([0, 1, 2, 3, 4, 5])

In [24]:
# 하나의 열에 접근 : 모든 행에 대해서 하나의 열에 접근
# 반환값 : 1d array
arr2[:,0]

array([ 0,  6, 12, 18])

In [25]:
# 하나의 값에 접근
# 3행 3열(0번째부터 세서 3행)
arr2[3,3]

21

In [26]:
# 여러개의 행 조회(2차원배열로 조회)
# 0번, 3번 행 만 조회
arr2[[0,3]]

array([[  0,   1,   2,   3,   4,   5],
       [ 18,  19,  20,  21,  22, 100]])

In [27]:
# 여러개의 열 조회(0번째, 2번째 열만 선택해서 조회)
arr2[:,[0,2]]

array([[ 0,  2],
       [ 6,  8],
       [12, 14],
       [18, 20]])

In [28]:
# 2차원 배열 인덱싱을 통한 값 수정
# 하나의 행/열에 대해 모두 동일한 값으로 수정 : 전달하려는 값을 스칼라값으로 전달
# 서로 다른 값으로 수정 : 배열 요소 개수에 맞춰서 전달
# 하나의 값을 수정하는 예시
arr2[2] = 9
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [29]:
# 단일 값이 아닌 여러 값을 대입하고 싶으면 모양에 맞게 배열을 대입합니다
arr2[1] = [9, 9, 9, 99, 99, 99]
arr2

array([[  0,   1,   2,   3,   4,   5],
       [  9,   9,   9,  99,  99,  99],
       [  9,   9,   9,   9,   9,   9],
       [ 18,  19,  20,  21,  22, 100]])

In [30]:
# 3차원 배열 생성
# 구조 : 2개의 층(면), 4행 3열
# np.arange() => 0 ~ 23까지 24개를 집어넣고 3차원으로 재조정해보세요
arr3 = np.arange(0, 24).reshape(2, 4, 3)
np_print(arr3)


    type : <class 'numpy.ndarray'>
    shape : (2, 4, 3)
    dimension : 3
    dtype : int32
    data : 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [31]:
# 3차원 배열 인덱싱 : arr[면, 행, 열]
# 0번째 면(페이지)에 접근
arr3[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [32]:
# 0번째 면, 첫번째 행에 접근시켜주세요
arr3[0,1]

array([3, 4, 5])

In [33]:
# 1번째 면, 2번 행, 2번 열에 접근
arr3[1, 2, 2]

20

In [34]:
# 한 면을 통째로 바꾸고 싶다면 같은 크기의 2차원 배열을 대입해줍니다
arr3[0] = [[10, 20, 30],
[40, 50, 60],
[0, 0, 0],
[0, 0, 0]]

In [35]:
arr3

array([[[10, 20, 30],
        [40, 50, 60],
        [ 0,  0,  0],
        [ 0,  0,  0]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [36]:
# 여러개의 인덱싱을 배열로 전달
# (행0, 열0), (행1, 열1), (행2, 열2)
# 3차원 배열일 경우에 : [페이지, [[0, 1, 2], [0, 1, 2]]]
# arr3[면, 행, 열] -> 만약 여러 단위를 조회할 대는 이중리스트로 입력
# 삼중리스트 입력시 이중리스트 요소를 반복
print(arr3[0])
print("----------------------")
print(arr3[0, [[0, 1, 2],[0, 2, 3]]])

[[10 20 30]
 [40 50 60]
 [ 0  0  0]
 [ 0  0  0]]
----------------------
[[[10 20 30]
  [40 50 60]
  [ 0  0  0]]

 [[10 20 30]
  [ 0  0  0]
  [ 0  0  0]]]


In [37]:
# 내부 요소 인덱싱시 일반 리스트를 사용하는 경우
# 줄 단위로 가져오는게 아니라 내부 요소 하나하나를 단위로 가져옴
arr3[0, [0, 1, 2], [0, 1, 2]]

array([10, 50,  0])

#### 2. 슬라이싱 : 여러 개의 요소에 대해 참조
- axis 별로 범위 지정
    - from_idnex : 시작 인덱스(포함), 0일 경우 생략 가능
    - to_index : 종료 인덱스(미포함), 마지막 인덱스일 경우 생략 가능
    - step : 연속되지 않은 범위의 경우 간격 지정
- 열만 조회하는 경우 : 전체 행에 슬라이싱으로 접근 후 특정 열을 조회

In [40]:
# 0부터 23까지 1씩 증가하는 정수값을 가지는 1차원배열을 변수 a 에 저장해서 조회해주세요
a = np.arange(0, 24)
np_print(a)


    type : <class 'numpy.ndarray'>
    shape : (24,)
    dimension : 1
    dtype : int32
    data : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [41]:
# 1차원 배열 슬라이싱 : 1부터 4번까지 접근
a[1:5]

array([1, 2, 3, 4])

In [55]:
# 1번부터 14번까지 2개씩 건너뛰면서 접근해주세요
a[1: 15 : 2]

array([ 1,  3,  5,  7,  9, 11, 13])

In [56]:
# 2차원 배열( 6 * 4 )로 a의 형태를 바꿔 변수 b에 저장해주시고 화면에 찍어주세요
b = a.reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [57]:
# 2차원 배열 슬라이싱 : 1행부터 4행까지 접근
# 2d_array[행(:열:간격)]
b[0:4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
# 1행 부터 4행에 대해서, 2열부터 3열까지 접근
b[1:5, 2:4]

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [59]:
# 2차원배열 슬라이싱을 통한 값 수정
# 1행부터 4행에 대해 2열부터 3열까지의 모든 배열에 대해서 수정
s_arr = b[1:5, 2:]
s_arr

array([[ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [70]:
# s_arr의 0번째 행과 마지막 열을 제외한 모든 값을 99 로 수정
s_arr[1:4, 0:1] = 99
s_arr

array([[ 6,  7],
       [99, 11],
       [99, 15],
       [99, 19]])

In [71]:
list1 = [1, 2, 3]
list2 = list1

In [72]:
list2[0] = 10
print(list1, list2)

[10, 2, 3] [10, 2, 3]


In [73]:
# 얕은복사로 인한 원본 배열의 변경
b    # 위에서 s_arr를 바꿧는데 b도 바뀌어있다

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11],
       [12, 13, 99, 15],
       [16, 17, 99, 19],
       [20, 21, 22, 23]])

In [ ]:
# 2차원 배열 슬라이싱 : 연속되지 않은 범위의 열(컬럼)에 대한 인덱싱
# step1. 전체 행에 대해서 접근
# step2. 여러 개의 열 인덱싱 배열 전달
# b의 전체 행 + 1, 3번 열을 조회해주세요

In [86]:
b[:,[1,3]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [21, 23]])

### 연습문제

아래 정보는 학생들의 학번, 영어 성적, 국어성적, 수학 성적 정보입니다.<br>
해당 정보를 첫번째 행(row)에 학번, 두번째 행에 영어성적, 세번째 행에 국어성적, 네번째 행에 수학 성적을
저장한 배열로 만들고 학생별로 영어 성적을 오름차순 기준으로 각 열(column)을 정렬하세요

<img src='img/sort_q1.png' align='left'>

In [87]:
data = [[1, 2, 3, 4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]]
arr = np.array(data)

In [88]:
arr

array([[ 1,  2,  3,  4],
       [70, 97, 45, 56],
       [87, 84, 33, 67],
       [46, 80, 75, 78]])

In [110]:
# argsort()를 이용해 정렬순번을 바꿔주세요
# 영어성적을 기준으로 했을때 정렬순번 얻기
i = np.argsort(arr[1])
np.sort(i)

array([0, 1, 2, 3], dtype=int64)

In [118]:
# 먼저 행(row)지정 후 열(column)지정을 합니다
# 현재 학번, 영어, 수학, 국어 서적을 모두 보여ㅜ저야 하므로
# row는 전체지정을 하되, 컬럼순번이 성적순이므로 , 위의 i를 활용해 컬럼을 지정하면 됩니다.
arr[:, i]

array([[ 3,  4,  1,  2],
       [45, 56, 70, 97],
       [33, 67, 87, 84],
       [75, 78, 46, 80]])